compile:
  c : 'gcc -w -std=c11 -O2 "[PROBLEM_DIR]" -D [GRADER_DEFINE] -o "[PROBLEM_DIR]/subject_binary"'
  cpp : 'g++ -w -std=c++17 -O2 "[PROBLEM_DIR]" -D [GRADER_DEFINE] -o "[PROBLEM_DIR]/subject_binary"'

