problem_dir : ./problems/[PROBLEM_ID]
grader_define : __KIYAGO__
subject_src : subject_src.cc
subject_bin : subject_bin
cmp_out : compile_space/cmp_out.txt
cmp_err : compile_space/cmp_err.txt

archive_dir : ./archives/[USER_ID]/[PROBLEM_ID]/[TIMESTAMP].cc